version: "3.9"

x-nginx-conf:
  &nginx-conf
  type: bind
  source: ./nginx/conf.d
  target: /

services:
  nbas-nginx:
    container_name: nbas-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - <<: *nginx-conf
        target:  /etc/nginx/conf.d
      - ./nginx/default/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nbas-reactjs
      - nbas-api
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  nbas-api:
    container_name: nbas-api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: ./api/app
        target: /app/
    depends_on:
      - nbas-mysql
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  nbas-reactjs:
    container_name: nbas-reactjs
    build:
      context: reactjs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./reactjs/my-app/src
        target: /app/src
      - type: bind
        source: ./reactjs/my-app/public
        target: /app/public
      - type: bind
        source: ./reactjs/my-app/tsconfig.json
        target: /app/tsconfig.json
      - type: bind
        source: ./reactjs/my-app/.env.development
        target: /app/.env.development
      - type: bind
        source: ./reactjs/my-app/.env.production
        target: /app/.env.production
    depends_on:
      - nbas-mysql
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  nbas-mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
    - mysql-data:/var/lib/mysql
    - ./db:/docker-entrypoint-initdb.d
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  mysql-data:
