version: "3.9"

services:
  nbas-api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: ./api/app
        target: /app/
    depends_on:
      - nbas-mysql
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  nbas-reactjs:
    build:
      context: reactjs
      dockerfile: Dockerfile
      args:
        FIREBASE_APIKEY: ${FIREBASE_APIKEY}
        FIREBASE_AUTHDOMAIN: ${FIREBASE_AUTHDOMAIN}
        FIREBASE_PROJECTID: ${FIREBASE_PROJECTID}
        FIREBASE_STORAGEBUCKET: ${FIREBASE_STORAGEBUCKET}
        FIREBASE_MESSAGINGSENDERID: ${FIREBASE_MESSAGINGSENDERID}
        FIREBASE_APPID: ${FIREBASE_APPID}
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./reactjs/my-app/src
        target: /app/src
      - type: bind
        source: ./reactjs/my-app/public
        target: /app/public
      - type: bind
        source: ./reactjs/my-app/tsconfig.json
        target: /app/tsconfig.json
    depends_on:
      - nbas-mysql
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  nbas-mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
    - mysql-data:/var/lib/mysql
    - ./db:/docker-entrypoint-initdb.d
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  mysql-data:
