CREATE TABLE `nbas`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `nbas`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `nbas`.`team_player` (
  `id_team` INT NOT NULL,
  `id_player` INT NOT NULL,
  PRIMARY KEY (`id_player`, `id_team`));

CREATE USER `nbas-user`@`%` IDENTIFIED WITH 'mysql_native_password' AS '*E59FFD968B8E6417EFF2E3D2C0F3BDA3996B476A' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON `nbas`.* TO `nbas-user`@`%`;
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON `nbas`.* TO `nbas-user`@`%`;

ALTER TABLE `nbas`.`teams` ADD UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE;
