FROM node:17-alpine3.12

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

#COPY ./package*.json ./

#RUN npm install

#RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

#CMD ["npm", "start"]
